import { Card } from "@/types/game";
import { nanoid } from "nanoid";

export const INITIAL_DECK: Card[] = [
  {
    id: nanoid(),
    type: 'SZEMÉLY',
    title: `Szálasi Ferenc`,
    description: `A Nyilaskeresztes Párt vezetője, aki a második világháború végén külső katonai és politikai támogatással került Magyarország élére.`,
    chain: '1944_oktberben_budapesten_szlasi_ferenc_nmet_tmogatssal_hatalomra_kerl',
  },
  {
    id: nanoid(),
    type: 'HELYSZÍN',
    title: `Budapest`,
    description: `Budapest volt az állami döntéshozatal központja, ahol a hatalomváltás intézményesen megjelent.`,
    chain: '1944_oktberben_budapesten_szlasi_ferenc_nmet_tmogatssal_hatalomra_kerl',
  },
  {
    id: nanoid(),
    type: 'ESEMÉNY',
    title: `német támogatással hatalomra kerül`,
    description: `A hatalomátvétel nem választási folyamat eredménye volt, hanem külső beavatkozással kikényszerített politikai fordulat.`,
    chain: '1944_oktberben_budapesten_szlasi_ferenc_nmet_tmogatssal_hatalomra_kerl',
  },
  {
    id: nanoid(),
    type: 'IDŐPONT',
    title: `1944`,
    description: `felhasználható:
– háborús összeomlás időszaka
– külső befolyás erősödése`,
    chain: '1944_oktberben_budapesten_szlasi_ferenc_nmet_tmogatssal_hatalomra_kerl',
    year: 1944,
  },
  {
    id: nanoid(),
    type: 'SZEMÉLY',
    title: `Hóman Bálint`,
    description: `Történész és politikus, aki korábbi kormányzati szerepe miatt a háború után népbíróság elé került.`,
    chain: '1948ban_a_parlamentben_tildy_zoltn_lemondsra_knyszerl',
  },
  {
    id: nanoid(),
    type: 'HELYSZÍN',
    title: `Vác`,
    description: `Vác a háború utáni politikai felelősségre vonások egyik börtönhelyszíne volt.`,
    chain: '1948ban_a_parlamentben_tildy_zoltn_lemondsra_knyszerl',
  },
  {
    id: nanoid(),
    type: 'ESEMÉNY',
    title: `életfogytiglani börtönbüntetést kap`,
    description: `A népbírósági ítélet a politikai és jogi elszámoltatás részeként született meg.`,
    chain: '1948ban_a_parlamentben_tildy_zoltn_lemondsra_knyszerl',
  },
  {
    id: nanoid(),
    type: 'IDŐPONT',
    title: `1946`,
    description: `felhasználható:
– jogi elszámoltatás időszaka
– politikai múlt lezárása`,
    chain: '1948ban_a_parlamentben_tildy_zoltn_lemondsra_knyszerl',
    year: 1946,
  },
  {
    id: nanoid(),
    type: 'SZEMÉLY',
    title: `Tildy Zoltán`,
    description: `Kisgazdapárti politikus, Magyarország köztársasági elnöke 1946–1948 között.`,
    chain: '1948ban_a_parlamentben_tildy_zoltn_lemondsra_knyszerl',
  },
  {
    id: nanoid(),
    type: 'HELYSZÍN',
    title: `Parlament`,
    description: `A Parlament az államfői és alkotmányos döntések hivatalos helyszíne volt.`,
    chain: '1948ban_a_parlamentben_tildy_zoltn_lemondsra_knyszerl',
  },
  {
    id: nanoid(),
    type: 'ESEMÉNY',
    title: `lemondásra kényszerül`,
    description: `A lemondás politikai nyomásgyakorlás eredményeként történt, a hatalmi viszonyok átalakulása során.`,
    chain: '1948ban_a_parlamentben_tildy_zoltn_lemondsra_knyszerl',
  },
  {
    id: nanoid(),
    type: 'IDŐPONT',
    title: `1948`,
    description: `felhasználható:
– politikai átrendeződés
– hatalmi koncentráció kezdete`,
    chain: '1948ban_a_parlamentben_tildy_zoltn_lemondsra_knyszerl',
    year: 1948,
  },
  {
    id: nanoid(),
    type: 'SZEMÉLY',
    title: `Gerő Ernő`,
    description: `Kommunista politikus, a pártapparátus egyik kulcsfigurája.`,
    chain: '1947ben_budapesten_prtkongresszust_tartanak_ger_ern_rszvtelvel',
  },
  {
    id: nanoid(),
    type: 'HELYSZÍN',
    title: `Budapest`,
    description: `Budapest a pártvezetés központja volt.`,
    chain: '1947ben_budapesten_prtkongresszust_tartanak_ger_ern_rszvtelvel',
  },
  {
    id: nanoid(),
    type: 'ESEMÉNY',
    title: `Pártkongresszus`,
    description: `A pártkongresszus a hatalom koncentrációját szolgálta.`,
    chain: '1947ben_budapesten_prtkongresszust_tartanak_ger_ern_rszvtelvel',
  },
  {
    id: nanoid(),
    type: 'IDŐPONT',
    title: `1947`,
    description: `felhasználható: pártszervezeti átalakulás, ideológiai irányváltás`,
    chain: '1947ben_budapesten_prtkongresszust_tartanak_ger_ern_rszvtelvel',
    year: 1947,
  },
  {
    id: nanoid(),
    type: 'SZEMÉLY',
    title: `Rákosi Mátyás`,
    description: `A kommunista párt vezetője, a rendszer kiépítésének fő alakja.`,
    chain: '1948ban_az_ipari_ltestmnyeket_llamostjk_rkosi_mtys_vezetsvel',
  },
  {
    id: nanoid(),
    type: 'HELYSZÍN',
    title: `Gyár`,
    description: `A gyár az ipari termelés és tulajdonváltás szimbóluma.`,
    chain: '1948ban_az_ipari_ltestmnyeket_llamostjk_rkosi_mtys_vezetsvel',
  },
  {
    id: nanoid(),
    type: 'ESEMÉNY',
    title: `Államosítás`,
    description: `Az államosítás a gazdasági hatalom állami kézbe vonását jelentette.`,
    chain: '1948ban_az_ipari_ltestmnyeket_llamostjk_rkosi_mtys_vezetsvel',
  },
  {
    id: nanoid(),
    type: 'IDŐPONT',
    title: `1948`,
    description: `felhasználható: gazdasági átalakulás, tulajdonviszonyok megváltozása`,
    chain: '1948ban_az_ipari_ltestmnyeket_llamostjk_rkosi_mtys_vezetsvel',
    year: 1948,
  },
  {
    id: nanoid(),
    type: 'SZEMÉLY',
    title: `Rajk László`,
    description: `Kommunista politikus, belügyminiszter, később a rendszer áldozata.`,
    chain: '1949ben_rajk_lszl_ellen_koncepcis_pert_folytatnak',
  },
  {
    id: nanoid(),
    type: 'HELYSZÍN',
    title: `Zárt tárgyalás`,
    description: `A zárt tárgyalás a politikai igazságszolgáltatás eszköze volt.`,
    chain: '1949ben_rajk_lszl_ellen_koncepcis_pert_folytatnak',
  },
  {
    id: nanoid(),
    type: 'ESEMÉNY',
    title: `Koncepciós per`,
    description: `A koncepciós per politikai leszámolásként működött.`,
    chain: '1949ben_rajk_lszl_ellen_koncepcis_pert_folytatnak',
  },
  {
    id: nanoid(),
    type: 'IDŐPONT',
    title: `1949`,
    description: `felhasználható: politikai tisztogatás, belső hatalmi harc`,
    chain: '1949ben_rajk_lszl_ellen_koncepcis_pert_folytatnak',
    year: 1949,
  },
  {
    id: nanoid(),
    type: 'SZEMÉLY',
    title: `Mindszenty József`,
    description: `A katolikus egyház vezető alakja, bíboros.`,
    chain: '1950ben_mindszenty_jzsefet_letartztatjk',
  },
  {
    id: nanoid(),
    type: 'HELYSZÍN',
    title: `Egyházi intézmény`,
    description: `Az egyházi intézmények az állam és egyház konfliktusának terepei voltak.`,
    chain: '1950ben_mindszenty_jzsefet_letartztatjk',
  },
  {
    id: nanoid(),
    type: 'ESEMÉNY',
    title: `Letartóztatás`,
    description: `A letartóztatás az egyházi autonómia felszámolását célozta.`,
    chain: '1950ben_mindszenty_jzsefet_letartztatjk',
  },
  {
    id: nanoid(),
    type: 'IDŐPONT',
    title: `1950`,
    description: `felhasználható: egyház–állam konfliktus, ideológiai nyomás`,
    chain: '1950ben_mindszenty_jzsefet_letartztatjk',
    year: 1950,
  },
  {
    id: nanoid(),
    type: 'SZEMÉLY',
    title: `Farkas Mihály`,
    description: `Honvédelmi miniszter, a rendszer erőszakszervezeteinek irányítója.`,
    chain: '1951ben_tmeges_deportlsok_zajlanak_gyjttborokon_keresztl',
  },
  {
    id: nanoid(),
    type: 'HELYSZÍN',
    title: `Gyűjtőtábor`,
    description: `A gyűjtőtábor a kényszerintézkedések eszköze volt.`,
    chain: '1951ben_tmeges_deportlsok_zajlanak_gyjttborokon_keresztl',
  },
  {
    id: nanoid(),
    type: 'ESEMÉNY',
    title: `Deportálás`,
    description: `A deportálás társadalmi megfélemlítést szolgált.`,
    chain: '1951ben_tmeges_deportlsok_zajlanak_gyjttborokon_keresztl',
  },
  {
    id: nanoid(),
    type: 'IDŐPONT',
    title: `1951`,
    description: `felhasználható: társadalmi elnyomás, kényszerpolitika`,
    chain: '1951ben_tmeges_deportlsok_zajlanak_gyjttborokon_keresztl',
    year: 1951,
  },
  {
    id: nanoid(),
    type: 'SZEMÉLY',
    title: `Andics Erzsébet`,
    description: `Történész és pártideológus, a kommunista kultúrpolitika alakja.`,
    chain: '1952ben_moszkvban_andics_erzsbet_ideolgiai_propagandatevkenysget_folytat',
  },
  {
    id: nanoid(),
    type: 'HELYSZÍN',
    title: `Moszkva`,
    description: `Moszkva a szovjet ideológiai irányítás központja volt.`,
    chain: '1952ben_moszkvban_andics_erzsbet_ideolgiai_propagandatevkenysget_folytat',
  },
  {
    id: nanoid(),
    type: 'ESEMÉNY',
    title: `propagandatevékenység`,
    description: `A propaganda a politikai narratíva formálását szolgálta.`,
    chain: '1952ben_moszkvban_andics_erzsbet_ideolgiai_propagandatevkenysget_folytat',
  },
  {
    id: nanoid(),
    type: 'IDŐPONT',
    title: `1952`,
    description: `felhasználható: ideológiai befolyás; narratív irányítás`,
    chain: '1952ben_moszkvban_andics_erzsbet_ideolgiai_propagandatevkenysget_folytat',
    year: 1952,
  },
  {
    id: nanoid(),
    type: 'SZEMÉLY',
    title: `Sztálin`,
    description: `A Szovjetunió vezetője, meghatározó hatalmi szereplő.`,
    chain: '1953ban_sztlin_hallval_lezrul_egy_politikai_tisztogatsi_korszak',
  },
  {
    id: nanoid(),
    type: 'HELYSZÍN',
    title: `Szovjetunió`,
    description: `A Szovjetunió Kelet-Európa politikai központja volt.`,
    chain: '1953ban_sztlin_hallval_lezrul_egy_politikai_tisztogatsi_korszak',
  },
  {
    id: nanoid(),
    type: 'ESEMÉNY',
    title: `politikai tisztogatások lezárulása`,
    description: `A tisztogatások a diktatórikus hatalomgyakorlás eszközei voltak.`,
    chain: '1953ban_sztlin_hallval_lezrul_egy_politikai_tisztogatsi_korszak',
  },
  {
    id: nanoid(),
    type: 'IDŐPONT',
    title: `1953`,
    description: `felhasználható: diktatórikus kontroll; hatalmi fordulópont`,
    chain: '1953ban_sztlin_hallval_lezrul_egy_politikai_tisztogatsi_korszak',
    year: 1953,
  },
  {
    id: nanoid(),
    type: 'SZEMÉLY',
    title: `Nagy Imre`,
    description: `Politikus, miniszterelnök, reformtörekvések képviselője.`,
    chain: '1954ben_megszntetik_az_internltborok_rendszert',
  },
  {
    id: nanoid(),
    type: 'HELYSZÍN',
    title: `Internálótábor`,
    description: `Az internálótábor az elnyomó intézkedések helyszíne volt.`,
    chain: '1954ben_megszntetik_az_internltborok_rendszert',
  },
  {
    id: nanoid(),
    type: 'ESEMÉNY',
    title: `internálási rendszer megszüntetése`,
    description: `Az internálás megszüntetése reformlépésnek számított.`,
    chain: '1954ben_megszntetik_az_internltborok_rendszert',
  },
  {
    id: nanoid(),
    type: 'IDŐPONT',
    title: `1954`,
    description: `felhasználható: enyhülési politika; reformkezdet`,
    chain: '1954ben_megszntetik_az_internltborok_rendszert',
    year: 1954,
  },
  {
    id: nanoid(),
    type: 'SZEMÉLY',
    title: `Képes Géza`,
    description: `Költő és műfordító, a kulturális élet szereplője.`,
    chain: '1955ben_kpes_gza_visszatr_magyarorszgra',
  },
  {
    id: nanoid(),
    type: 'HELYSZÍN',
    title: `Határátkelő`,
    description: `A határátkelő a politikai mozgástér jelképe volt.`,
    chain: '1955ben_kpes_gza_visszatr_magyarorszgra',
  },
  {
    id: nanoid(),
    type: 'ESEMÉNY',
    title: `visszatérés`,
    description: `A visszatérés a kulturális enyhülés jele.`,
    chain: '1955ben_kpes_gza_visszatr_magyarorszgra',
  },
  {
    id: nanoid(),
    type: 'IDŐPONT',
    title: `1955`,
    description: `felhasználható: kulturális nyitás; személyes rehabilitáció`,
    chain: '1955ben_kpes_gza_visszatr_magyarorszgra',
    year: 1955,
  },
  {
    id: nanoid(),
    type: 'SZEMÉLY',
    title: `Maléter Pál`,
    description: `Katonatiszt, az 1956-os forradalom katonai vezetője.`,
    chain: '1956ban_tkln_malter_plt_letartztatjk_trgyals_kzben',
  },
  {
    id: nanoid(),
    type: 'HELYSZÍN',
    title: `Tököl`,
    description: `Tököl szovjet katonai tárgyalások helyszíne volt.`,
    chain: '1956ban_tkln_malter_plt_letartztatjk_trgyals_kzben',
  },
  {
    id: nanoid(),
    type: 'ESEMÉNY',
    title: `letartóztatás`,
    description: `A letartóztatás a megtorlás előkészítése volt.`,
    chain: '1956ban_tkln_malter_plt_letartztatjk_trgyals_kzben',
  },
  {
    id: nanoid(),
    type: 'IDŐPONT',
    title: `1956`,
    description: `felhasználható: fegyveres konfliktus; megtorlás kezdete`,
    chain: '1956ban_tkln_malter_plt_letartztatjk_trgyals_kzben',
    year: 1956,
  },
  {
    id: nanoid(),
    type: 'SZEMÉLY',
    title: `Kádár János`,
    description: `Kommunista politikus, a forradalom utáni rendszer vezetője.`,
    chain: '1957ben_a_forradalom_utni_megtorlsok_idszaka_kezddik',
  },
  {
    id: nanoid(),
    type: 'HELYSZÍN',
    title: `Egyetem`,
    description: `Az egyetemek a politikai tisztogatások szimbolikus terepei voltak.`,
    chain: '1957ben_a_forradalom_utni_megtorlsok_idszaka_kezddik',
  },
  {
    id: nanoid(),
    type: 'ESEMÉNY',
    title: `politikai megtorlás`,
    description: `A megtorlás a hatalom megszilárdítását szolgálta.`,
    chain: '1957ben_a_forradalom_utni_megtorlsok_idszaka_kezddik',
  },
  {
    id: nanoid(),
    type: 'IDŐPONT',
    title: `1957`,
    description: `felhasználható: konszolidáció erőszakkal; rendszermegerősítés`,
    chain: '1957ben_a_forradalom_utni_megtorlsok_idszaka_kezddik',
    year: 1957,
  },
  {
    id: nanoid(),
    type: 'SZEMÉLY',
    title: `Losonczy Géza`,
    description: `Újságíró és politikus, az 1956-os események szereplője.`,
    chain: '1958ban_losonczy_gza_fogvatartsa_sorn_lett_veszti',
  },
  {
    id: nanoid(),
    type: 'HELYSZÍN',
    title: `Fogvatartás`,
    description: `A fogvatartás az elszigetelés eszköze volt.`,
    chain: '1958ban_losonczy_gza_fogvatartsa_sorn_lett_veszti',
  },
  {
    id: nanoid(),
    type: 'ESEMÉNY',
    title: `halál fogságban`,
    description: `Halála a megtorlások következménye.`,
    chain: '1958ban_losonczy_gza_fogvatartsa_sorn_lett_veszti',
  },
  {
    id: nanoid(),
    type: 'IDŐPONT',
    title: `1958`,
    description: `felhasználható: politikai elhallgattatás; megtorlás következménye`,
    chain: '1958ban_losonczy_gza_fogvatartsa_sorn_lett_veszti',
    year: 1958,
  },
  {
    id: nanoid(),
    type: 'SZEMÉLY',
    title: `Erdei Ferenc`,
    description: `Politikus és szociológus, agrárpolitikai döntések résztvevője.`,
    chain: '1959ben_a_mezgazdasgi_beszolgltatsi_rendszer_mkdik',
  },
  {
    id: nanoid(),
    type: 'HELYSZÍN',
    title: `Vidék`,
    description: `A vidék a kollektivizálás terepe volt.`,
    chain: '1959ben_a_mezgazdasgi_beszolgltatsi_rendszer_mkdik',
  },
  {
    id: nanoid(),
    type: 'ESEMÉNY',
    title: `beszolgáltatás`,
    description: `A beszolgáltatás gazdasági kényszer.`,
    chain: '1959ben_a_mezgazdasgi_beszolgltatsi_rendszer_mkdik',
  },
  {
    id: nanoid(),
    type: 'IDŐPONT',
    title: `1959`,
    description: `felhasználható: kollektivizálás; gazdasági kényszer`,
    chain: '1959ben_a_mezgazdasgi_beszolgltatsi_rendszer_mkdik',
    year: 1959,
  },
  {
    id: nanoid(),
    type: 'SZEMÉLY',
    title: `Bibó István`,
    description: `Jogtudós és politikai gondolkodó.`,
    chain: '1960ban_bib_istvn_amnesztiban_rszesl',
  },
  {
    id: nanoid(),
    type: 'HELYSZÍN',
    title: `Belső száműzetés`,
    description: `A belső száműzetés a politikai elszigetelés formája volt.`,
    chain: '1960ban_bib_istvn_amnesztiban_rszesl',
  },
  {
    id: nanoid(),
    type: 'ESEMÉNY',
    title: `amnesztia`,
    description: `Az amnesztia korlátozott politikai enyhülést jelentett.`,
    chain: '1960ban_bib_istvn_amnesztiban_rszesl',
  },
  {
    id: nanoid(),
    type: 'IDŐPONT',
    title: `1960`,
    description: `felhasználható: politikai enyhülés; részleges rehabilitáció`,
    chain: '1960ban_bib_istvn_amnesztiban_rszesl',
    year: 1960,
  },
  {
    id: nanoid(),
    type: 'SZEMÉLY',
    title: `Horthy Miklós`,
    description: `Magyarország kormányzója a korszakban.`,
    chain: '1941ben_magyarorszg_belp_a_msodik_vilghborba',
  },
  {
    id: nanoid(),
    type: 'HELYSZÍN',
    title: `Magyarország`,
    description: `Az ország külpolitikai döntéshozatalának tere.`,
    chain: '1941ben_magyarorszg_belp_a_msodik_vilghborba',
  },
  {
    id: nanoid(),
    type: 'ESEMÉNY',
    title: `hadba lépés`,
    description: `A hadba lépés stratégiai döntés volt.`,
    chain: '1941ben_magyarorszg_belp_a_msodik_vilghborba',
  },
  {
    id: nanoid(),
    type: 'IDŐPONT',
    title: `1941`,
    description: `felhasználható: háborús elköteleződés; külpolitikai fordulat`,
    chain: '1941ben_magyarorszg_belp_a_msodik_vilghborba',
    year: 1941,
  },
  {
    id: nanoid(),
    type: 'SZEMÉLY',
    title: `Ortutay Gyula`,
    description: `Néprajzkutató és politikus, később kultúrpolitikai szereplő.`,
    chain: '1940ben_a_kossuth_tren_ortutay_gyula_politikai_beszdet_mond',
  },
  {
    id: nanoid(),
    type: 'HELYSZÍN',
    title: `Kossuth tér`,
    description: `A Kossuth tér a nyilvános politikai megszólalások kiemelt helyszíne.`,
    chain: '1940ben_a_kossuth_tren_ortutay_gyula_politikai_beszdet_mond',
  },
  {
    id: nanoid(),
    type: 'ESEMÉNY',
    title: `politikai beszéd`,
    description: `A politikai beszéd a nyilvános ideológiai kommunikáció eszköze.`,
    chain: '1940ben_a_kossuth_tren_ortutay_gyula_politikai_beszdet_mond',
  },
  {
    id: nanoid(),
    type: 'IDŐPONT',
    title: `1940`,
    description: `felhasználható: politikai mobilizáció; nyilvános megszólalás`,
    chain: '1940ben_a_kossuth_tren_ortutay_gyula_politikai_beszdet_mond',
    year: 1940,
  },
  {
    id: nanoid(),
    type: 'SZEMÉLY',
    title: `Piros László`,
    description: `Kommunista politikus, későbbi belügyminiszter.`,
    chain: '1942ben_piros_lszl_szovjet_katonai_bzison_trgyalst_folytat',
  },
  {
    id: nanoid(),
    type: 'HELYSZÍN',
    title: `Szovjet katonai bázis`,
    description: `A katonai bázis a titkos diplomácia helyszíne volt.`,
    chain: '1942ben_piros_lszl_szovjet_katonai_bzison_trgyalst_folytat',
  },
  {
    id: nanoid(),
    type: 'ESEMÉNY',
    title: `tárgyalás`,
    description: `A tárgyalás háttérkapcsolatok kialakítását szolgálta.`,
    chain: '1942ben_piros_lszl_szovjet_katonai_bzison_trgyalst_folytat',
  },
  {
    id: nanoid(),
    type: 'IDŐPONT',
    title: `1942`,
    description: `felhasználható: titkos diplomácia; politikai kapcsolatépítés`,
    chain: '1942ben_piros_lszl_szovjet_katonai_bzison_trgyalst_folytat',
    year: 1942,
  },
  {
    id: nanoid(),
    type: 'SZEMÉLY',
    title: `Péter Gábor`,
    description: `Az Államvédelmi Hatóság vezetője, a megtorló apparátus irányítója.`,
    chain: 'az_vh_szkhzban_pter_gbor_rszvtelvel_titkos_trgyals_zajlik',
  },
  {
    id: nanoid(),
    type: 'HELYSZÍN',
    title: `ÁVH székház`,
    description: `Az ÁVH székház a politikai rendőrség központja volt.`,
    chain: 'az_vh_szkhzban_pter_gbor_rszvtelvel_titkos_trgyals_zajlik',
  },
  {
    id: nanoid(),
    type: 'ESEMÉNY',
    title: `titkos tárgyalás`,
    description: `A titkos tárgyalás a belső hatalmi viszonyok átrendezését jelezte.`,
    chain: 'az_vh_szkhzban_pter_gbor_rszvtelvel_titkos_trgyals_zajlik',
  },
  {
    id: nanoid(),
    type: 'IDŐPONT',
    title: `1953`,
    description: `felhasználható:
– belső elszámoltatás időszaka
– titkosszolgálati átrendeződés`,
    chain: 'az_vh_szkhzban_pter_gbor_rszvtelvel_titkos_trgyals_zajlik',
    year: 1953,
  },
  {
    id: nanoid(),
    type: 'SZEMÉLY',
    title: `Apró Antal`,
    description: `Kommunista politikus, a rendszer kontinuitásának biztosítója.`,
    chain: 'az_andrssy_ton_apr_antal_hatalmi_tmenetet_menedzsel',
  },
  {
    id: nanoid(),
    type: 'HELYSZÍN',
    title: `Andrássy út`,
    description: `Az Andrássy út a politikai elit intézményeinek helyszíne volt.`,
    chain: 'az_andrssy_ton_apr_antal_hatalmi_tmenetet_menedzsel',
  },
  {
    id: nanoid(),
    type: 'ESEMÉNY',
    title: `hatalomátmentés`,
    description: `A hatalomátmentés az ideológiai alkalmazkodás eszköze.`,
    chain: 'az_andrssy_ton_apr_antal_hatalmi_tmenetet_menedzsel',
  },
  {
    id: nanoid(),
    type: 'IDŐPONT',
    title: `1957`,
    description: `felhasználható:
– hatalmi folytonosság biztosítása
– ideológiai alkalmazkodás kezdete`,
    chain: 'az_andrssy_ton_apr_antal_hatalmi_tmenetet_menedzsel',
    year: 1957,
  },
  {
    id: nanoid(),
    type: 'SZEMÉLY',
    title: `Münnich Ferenc`,
    description: `Kommunista politikus, belügyi és katonai vezető, a megtorló apparátus egyik kulcsfigurája.`,
    chain: '1953ban_felszmoljk_a_recski_internltbort_mnnich_ferenc_belgyi_irnytsa_idejn',
  },
  {
    id: nanoid(),
    type: 'HELYSZÍN',
    title: `Recsk`,
    description: `Recsk a politikai internálás legismertebb magyarországi helyszíne volt.`,
    chain: '1953ban_felszmoljk_a_recski_internltbort_mnnich_ferenc_belgyi_irnytsa_idejn',
  },
  {
    id: nanoid(),
    type: 'ESEMÉNY',
    title: `internálótábor felszámolása`,
    description: `Az internálótábor felszámolása a politikai irányváltás egyik jele.`,
    chain: '1953ban_felszmoljk_a_recski_internltbort_mnnich_ferenc_belgyi_irnytsa_idejn',
  },
  {
    id: nanoid(),
    type: 'IDŐPONT',
    title: `1953`,
    description: `felhasználható: politikai enyhülés; elnyomó intézmények átalakítása`,
    chain: '1953ban_felszmoljk_a_recski_internltbort_mnnich_ferenc_belgyi_irnytsa_idejn',
    year: 1953,
  },
  {
    id: nanoid(),
    type: 'SZEMÉLY',
    title: `Kéthly Anna`,
    description: `Szociáldemokrata politikus, a demokratikus ellenzék meghatározó alakja.`,
    chain: '1948ban_kthly_anna_klfldre_knyszerl_emigrciban_folytat_ellenzki_tevkenysget',
  },
  {
    id: nanoid(),
    type: 'HELYSZÍN',
    title: `Külföldi emigráció`,
    description: `A külföldi emigráció az ellenzéki politikai mozgástér egyik formája volt.`,
    chain: '1948ban_kthly_anna_klfldre_knyszerl_emigrciban_folytat_ellenzki_tevkenysget',
  },
  {
    id: nanoid(),
    type: 'ESEMÉNY',
    title: `emigráció és ellenállás`,
    description: `Az emigráció a belpolitikai ellehetetlenítés következménye.`,
    chain: '1948ban_kthly_anna_klfldre_knyszerl_emigrciban_folytat_ellenzki_tevkenysget',
  },
  {
    id: nanoid(),
    type: 'IDŐPONT',
    title: `1948`,
    description: `felhasználható: politikai száműzetés; külső ellenzék kialakulása`,
    chain: '1948ban_kthly_anna_klfldre_knyszerl_emigrciban_folytat_ellenzki_tevkenysget',
    year: 1948,
  },
  {
    id: nanoid(),
    type: 'SZEMÉLY',
    title: `Aczél György`,
    description: `Kommunista politikus, később a kultúrpolitika meghatározó alakja.`,
    chain: '1949tl_a_hatrlezrs_s_a_kulturlis_ellenrzs_rendszere_megersdik',
  },
  {
    id: nanoid(),
    type: 'HELYSZÍN',
    title: `Határ`,
    description: `A határ a fizikai és információs elszigetelés jelképe volt.`,
    chain: '1949tl_a_hatrlezrs_s_a_kulturlis_ellenrzs_rendszere_megersdik',
  },
  {
    id: nanoid(),
    type: 'ESEMÉNY',
    title: `határlezárás és cenzúra megerősítése`,
    description: `A határlezárás és cenzúra az ideológiai kontroll része.`,
    chain: '1949tl_a_hatrlezrs_s_a_kulturlis_ellenrzs_rendszere_megersdik',
  },
  {
    id: nanoid(),
    type: 'IDŐPONT',
    title: `1949`,
    description: `felhasználható: elszigetelés; információkontroll`,
    chain: '1949tl_a_hatrlezrs_s_a_kulturlis_ellenrzs_rendszere_megersdik',
    year: 1949,
  },
];
